config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users
  post 'user/:id/expert-search', to: 'users#expert_search', as: 'expert_search'
  post 'user/:id/:friend_id', to: 'users#add_friend', as: 'add_friend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'open-uri'

class User < ActiveRecord::Base
  before_save :generate_shortened_url
  after_create :scrape_website_url

  has_many :headings
  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key:  :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  validates_presence_of :name, :website_url
  validates_uniqueness_of :name
  validates_format_of :website_url, with: URI::regexp(%w(http https))


  def all_friends
    (friends + inverse_friends).uniq
  end

  def not_friends
    all_friend_ids = all_friends.map(&:id) + [self.id]
    User.where('id NOT IN (?)', all_friend_ids)
  end

  def find_related_headings_by_topic(topic)
    # tokenize the topic text like the heading text
    topic_tags = topic.to_s.downcase.gsub('-', ' ').gsub(/[^[:word:]\s]/, '').split.uniq
    all_friend_ids = all_friends.map(&:id) + [self.id]
    #find headings containing all tags from topic belonging to non-friends and not yourself
    Heading.where('tags @> ARRAY[?]::text[] AND user_id NOT IN (?)', topic_tags, all_friend_ids)
  end

  def connection_to(another_user)
    if another_user.all_friends.include?(self)
      "#{self.name} => #{another_user.name}"
    else
      #probably can go deeper to find friends of friends of friends ...
      #this implementation only look for common friend(s) between searcher and expert
      common_friends = another_user.all_friends & self.all_friends
      if common_friends.present?
        "#{self.name} => #{common_friends.map(&:name).join(', ')} => #{another_user.name}"
      else
        "no common friends"
      end
    end
  end

  private

  def generate_shortened_url
    begin
      shortened_website_url = Google::UrlShortener::Url.new(long_url: self.website_url).shorten!
      self.shortened_website_url = shortened_website_url
    rescue
      self.shortened_website_url = nil
    end
  end

  def scrape_website_url
    unless Rails.env.test?
      doc = Nokogiri::HTML(open(website_url))
      headings = doc.css('h1, h2, h3').map(&:text)

      headings.each do |heading|
        # the intention is to tokenize a heading text into tags, basically a primitive imitation of Elasticsearch tokenizers
        tags = heading.to_s.downcase.gsub('-', ' ').gsub(/[^[:word:]\s]/, '').split.uniq
        self.headings.create(original_text: heading, tags: tags)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  layout 'application'

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find_by_id(params[:id])

    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(permitted_params)

    if @user.save
      redirect_to root_path, notice: 'New user added succesfully'
    else
      render :new
    end
  end

  def expert_search
    @user = User.find_by_id(params[:id])
    @related_headings = @user.find_related_headings_by_topic(params[:topic])

    render partial: 'result_list', locals: { user: @user, headings: @related_headings }, content_type: 'text/html'
  end

  def add_friend
    @user = User.find_by_id(params[:id])
    @to_be_friend = User.find_by_id(params[:friend_id])

    if @user && @to_be_friend
      @user.friends << @to_be_friend
      redirect_to user_path(@user), notice: "You have added #{@to_be_friend} as a friend."
    else
      redirect_to user_path(@user), alert: "Something is wrong."
    end
  end

  private

  def permitted_params
    params.require(:user).permit(:name, :website_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverlywellChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_result_list.html.slim
- if headings.present?

  table
    th Connection
    th Heading
    th Expert
    - headings.each do |heading|
      tr
        td
          = user.connection_to(heading.user)
        td
          = heading.original_text
        td
          = heading.user.name
- else
  p No experts found.

app/views/users/index.html.slim
h3 Everlywell Challenge by Quang Le

= link_to "Add new user", new_user_path
table
  th Name
  th Website URL
  th Shortened Website URL
  th Number of Friends
  - @users.each do |user|
    tr
      td = user.name
      td = link_to user.website_url
      td = link_to  user.shortened_website_url
      td = user.all_friends.size
      td = link_to "Profile", user_path(user)

app/views/users/new.html.slim
h3 Add a new User
= form_for @user do |f|
  - if @user.errors.present?
    ul
      - @user.errors.full_messages.each do |msg|
        li= msg
  p Name:
  = f.text_field :name
  p Website URL:
  = f.text_field :website_url
  p
  = f.submit

p
  = link_to "Back", root_path

app/views/users/show.html.slim
h3
  = "#{@user.name}'s Profile"
p
  = "Name: #{@user.name}"
p
  = "Website URL: "
  = link_to @user.website_url
p
  = "Shortened website URL: "
  = link_to @user.shortened_website_url

h3 Find experts by topic:
= form_tag(expert_search_path(id: @user.id), { method: :post, remote: true }) do
  = text_field_tag "topic"
  = submit_tag "Search"
#result-container

h3 Friends List:
table
  - @user.all_friends.each do |friend|
    tr
      td
        = friend.name
      td
        = link_to "Profile", user_path(friend)

h3 Not Friends Yet:
table
  - @user.not_friends.each do |friend|
    tr
      td
        = friend.name
      td
        = link_to "Add friend", add_friend_path(id: @user.id, friend_id: friend.id), method: :post

h3 Headings:
table
  - @user.headings.each do |heading|
    tr
      td
        = heading.original_text

p
  = link_to "Back", root_path

javascript:
  $(document).ready( function() {
    $('form').on('ajax:success', function(event, data) {
      $('#result-container').html(data);
    });
  });